import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { Menu, Plus, Search, LogOut } from "lucide-react";

import { useAuth } from "../../context/AuthContext";
import { initials } from "../../lib/format";

/* ==========================================================
   Route → page title map (keeps the header honest)
========================================================== */

const TITLES = {
    "/": ["Dashboard", "Live status of every AI company you have built"],
    "/generate": ["Generate", "Describe an idea and let the agents build it"],
    "/generation": ["Live Workflow", "Watching your autonomous team execute"],
    "/projects": ["Projects", "Every startup generated by your account"],
    "/agents": ["Agents", "The six departments inside the company graph"],
    "/settings": ["Settings", "Account, session and platform preferences"],
};

function resolveTitle(pathname) {
    if (TITLES[pathname]) return TITLES[pathname];
    if (pathname.startsWith("/project/")) return ["Project", "Reports, files and live preview"];
    return ["AI Company OS", "Autonomous startup platform"];
}

function Header({ onMenu }) {
    const { user, logout } = useAuth();
    const navigate = useNavigate();
    const location = useLocation();

    const [query, setQuery] = useState("");

    const [title, subtitle] = resolveTitle(location.pathname);
    const name = user?.name || "User";

    function handleSearch(event) {
        event.preventDefault();
        const term = query.trim();
        navigate(term ? `/projects?q=${encodeURIComponent(term)}` : "/projects");
    }

    return (
        <header className="sticky top-0 z-30 border-b border-slate-400/10 bg-[#070814]/80 backdrop-blur-xl">
            <div className="flex h-16 items-center gap-4 px-4 sm:px-6 lg:px-8 xl:px-10">
                {/* Mobile menu */}
                <button onClick={onMenu} className="icon-btn lg:hidden" aria-label="Open navigation">
                    <Menu size={18} />
                </button>

                {/* Title */}
                <div className="min-w-0 flex-1">
                    <h1 className="truncate text-[15px] font-bold leading-tight text-slate-100">
                        {title}
                    </h1>
                    <p className="hidden truncate text-xs text-slate-500 sm:block">
                        {subtitle}
                    </p>
                </div>

                {/* Search */}
                <form
                    onSubmit={handleSearch}
                    className="hidden items-center gap-2.5 rounded-xl border border-slate-400/12 bg-white/[0.03] px-3.5 py-2 w-72 transition focus-within:border-violet-400/60 focus-within:bg-white/[0.05] xl:flex"
                >
                    <Search size={15} className="shrink-0 text-slate-500" />

                    <input
                        value={query}
                        onChange={(event) => setQuery(event.target.value)}
                        placeholder="Search projects…"
                        className="w-full bg-transparent text-sm text-slate-200 placeholder:text-slate-600"
                    />

                    {query && (
                        <kbd className="rounded bg-slate-500/15 px-1.5 py-0.5 text-[10px] text-slate-400">
                            ↵
                        </kbd>
                    )}
                </form>

                {/* New project */}
                <Link to="/generate" className="btn-primary hidden text-sm sm:inline-flex">
                    <Plus size={16} />
                    New Project
                </Link>

                {/* Identity */}
                <div className="flex items-center gap-3 rounded-xl border border-slate-400/12 bg-white/[0.03] py-1.5 pl-1.5 pr-2 sm:pr-3">
                    <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500 to-indigo-600 text-xs font-bold text-white">
                        {initials(name)}
                    </span>

                    <div className="hidden min-w-0 md:block">
                        <p className="truncate text-xs font-semibold text-slate-200">{name}</p>
                        <p className="flex items-center gap-1.5 text-[10px] text-slate-500">
                            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                            Online
                        </p>
                    </div>

                    <button
                        onClick={logout}
                        title="Log out"
                        aria-label="Log out"
                        className="hidden h-8 w-8 items-center justify-center rounded-lg text-slate-500 transition hover:bg-red-500/10 hover:text-red-300 sm:flex"
                    >
                        <LogOut size={15} />
                    </button>
                </div>

                <span className="sr-only">AI Company OS application header</span>
            </div>
        </header>
    );
}

export default Header;
