import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Menu, Search, Bell } from "lucide-react";

import { useAuth } from "../../context/AuthContext";
import { initials } from "../../lib/format";

/* ==========================================================
   Route → page title map (keeps the header honest)
========================================================== */

const TITLES = {
    "/": ["Dashboard", "Live status of every AI company you have built"],
    "/generate": ["Generate", "Describe an idea and let the agents build it"],
    "/generation": ["Live Workflow", "Watching your autonomous team execute"],
    "/projects": ["Projects", "Every startup generated by your account"],
    "/agents": ["Agents", "The six departments inside the company graph"],
    "/knowledge": ["Knowledge", "Reports produced across your projects"],
    "/analytics": ["Analytics", "Execution history and outcomes"],
    "/settings": ["Settings", "Account, session and platform preferences"],
};

function resolveTitle(pathname) {
    if (TITLES[pathname]) return TITLES[pathname];
    if (pathname.startsWith("/project/")) {
        return ["Project", "Reports, files and live preview"];
    }
    return ["AI Company OS", "Autonomous startup platform"];
}

function Header({ onMenu }) {
    const { user } = useAuth();
    const navigate = useNavigate();
    const location = useLocation();

    const [query, setQuery] = useState("");
    const inputRef = useRef(null);

    const [title, subtitle] = resolveTitle(location.pathname);
    const name = user?.name || "User";

    function handleSearch(event) {
        event.preventDefault();

        const term = query.trim();
        navigate(term ? `/projects?q=${encodeURIComponent(term)}` : "/projects");
    }

    /* ⌘K / Ctrl+K focuses the global search */
    useEffect(() => {
        function onKeyDown(event) {
            const isCommandK =
                (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k";

            if (!isCommandK) return;

            event.preventDefault();
            inputRef.current?.focus();
            inputRef.current?.select();
        }

        window.addEventListener("keydown", onKeyDown);
        return () => window.removeEventListener("keydown", onKeyDown);
    }, []);

    /* Leave the projects screen when the box is cleared */
    function onBlurReset(event) {
        if (!event.target.value.trim() && location.pathname !== "/projects") return;
        if (!event.target.value.trim()) navigate("/projects", { replace: true });
    }

    return (
        <header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-[var(--color-line)] bg-[var(--color-canvas)]/85 px-4 backdrop-blur-xl sm:gap-4 sm:px-6 lg:px-8 xl:px-10">
            {/* Mobile menu */}
            <button
                onClick={onMenu}
                className="icon-btn shrink-0 lg:hidden"
                aria-label="Open navigation"
            >
                <Menu size={18} />
            </button>

            {/* Page title area */}
            <div className="min-w-0 flex-1">
                <h1 className="truncate text-[15px] font-bold leading-tight text-slate-100">
                    {title}
                </h1>
                <p className="hidden truncate text-xs text-slate-500 sm:block">
                    {subtitle}
                </p>
            </div>

            {/* Search */}
            <form
                onSubmit={handleSearch}
                className="hidden w-[340px] shrink-0 items-center gap-2.5 rounded-xl border border-[var(--color-line)] bg-white/[0.03] px-3.5 py-2.5 transition focus-within:border-violet-400/60 focus-within:bg-white/[0.05] md:flex"
            >
                <Search size={15} className="shrink-0 text-slate-500" />

                <input
                    ref={inputRef}
                    value={query}
                    onChange={(event) => setQuery(event.target.value)}
                    onBlur={onBlurReset}
                    placeholder="Search anything..."
                    aria-label="Search projects"
                    className="w-full min-w-0 bg-transparent text-sm text-slate-200 placeholder:text-slate-600"
                />

                <kbd className="shrink-0 rounded-md border border-[var(--color-line)] px-1.5 py-0.5 text-[10px] text-slate-500">
                    ⌘K
                </kbd>
            </form>

            {/* Notifications */}
            <button
                type="button"
                className="icon-btn relative shrink-0"
                aria-label="Notifications"
            >
                <Bell size={16} />
                <span className="absolute right-2.5 top-2.5 h-1.5 w-1.5 rounded-full bg-violet-400 ring-2 ring-[var(--color-canvas)]" />
            </button>

            {/* Identity */}
            <button
                type="button"
                onClick={() => navigate("/settings")}
                title={name}
                aria-label="Open settings"
                className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-500 to-indigo-600 text-xs font-bold text-white transition hover:brightness-110"
            >
                {initials(name)}
            </button>
        </header>
    );
}

export default Header;
