import { useMemo } from "react";
import { BarChart3, CheckCircle2, Rocket, XCircle } from "lucide-react";

import PageHeader from "../components/ui/PageHeader";
import Panel from "../components/ui/Panel";
import StatCard from "../components/ui/StatCard";
import EmptyState from "../components/ui/EmptyState";
import { Skeleton } from "../components/ui/Skeleton";

import { useProjects } from "../hooks/useProjects";
import { countByStatus, formatDate } from "../lib/format";

/* ==========================================================
   Analytics — aggregated from GET /projects. There is no
   metrics endpoint, so every figure is the real history of
   the signed-in account.
========================================================== */

const CRUMBS = [{ label: "Home", to: "/" }, { label: "Analytics" }];
const DAYS = 14;

function dayKey(date) {
    return date.toISOString().slice(0, 10);
}

function buildSeries(projects) {
    const buckets = [];

    for (let offset = DAYS - 1; offset >= 0; offset -= 1) {
        const date = new Date();
        date.setHours(0, 0, 0, 0);
        date.setDate(date.getDate() - offset);

        buckets.push({
            key: dayKey(date),
            label: date.toLocaleDateString(undefined, { day: "numeric" }),
            count: 0,
        });
    }

    const index = new Map(buckets.map((bucket, i) => [bucket.key, i]));

    projects.forEach((project) => {
        if (!project.created_at) return;

        const at = index.get(dayKey(new Date(project.created_at)));
        if (at !== undefined) buckets[at].count += 1;
    });

    return buckets;
}

function Analytics() {
    const { projects, loading, error, reload } = useProjects();

    const counts = useMemo(() => countByStatus(projects), [projects]);
    const series = useMemo(() => buildSeries(projects), [projects]);
    const peak = Math.max(1, ...series.map((bucket) => bucket.count));

    const completed = counts.completed || 0;
    const running = counts.running || 0;
    const successRate = projects.length
        ? Math.round((completed / projects.length) * 100)
        : 0;

    if (error) {
        return (
            <EmptyState
                icon={XCircle}
                title="Could not load analytics"
                description={error}
                action={
                    <button onClick={reload} className="btn-ghost text-xs">
                        Try again
                    </button>
                }
            />
        );
    }

    return (
        <div className="space-y-7">
            <PageHeader
                crumbs={CRUMBS}
                eyebrow="Insights"
                title="Analytics"
                description="Run volume and outcomes across every startup generated by your account."
            />

            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <StatCard title="Total Runs" value={projects.length} icon={Rocket} tone="violet" hint="Projects created" loading={loading} />
                <StatCard title="Completed" value={completed} icon={CheckCircle2} tone="emerald" hint="Fully generated" loading={loading} />
                <StatCard title="Running" value={running} icon={BarChart3} tone="sky" hint="In progress now" loading={loading} />
                <StatCard title="Success Rate" value={`${successRate}%`} icon={CheckCircle2} tone="amber" hint="Completed / total" loading={loading} />
            </div>

            <Panel title="Runs per day" subtitle={`Last ${DAYS} days`} icon={BarChart3}>
                {loading ? (
                    <Skeleton className="h-48 w-full" />
                ) : projects.length === 0 ? (
                    <p className="py-16 text-center text-sm text-slate-500">
                        No runs recorded yet. Generate a startup to start collecting data.
                    </p>
                ) : (
                    <div className="flex h-48 items-end gap-1.5">
                        {series.map((bucket) => (
                            <div
                                key={bucket.key}
                                className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2 self-stretch"
                            >
                                <span className="mt-auto text-[10px] tabular-nums text-slate-500">
                                    {bucket.count || ""}
                                </span>

                                <div
                                    title={`${bucket.count} on ${formatDate(bucket.key)}`}
                                    className={
                                        bucket.count
                                            ? "w-full rounded-t-md bg-gradient-to-t from-violet-600/70 to-indigo-400/80"
                                            : "w-full rounded-t-md bg-white/[0.04]"
                                    }
                                    style={{
                                        height: bucket.count
                                            ? `${Math.max(8, (bucket.count / peak) * 100)}%`
                                            : "3px",
                                    }}
                                />

                                <span className="text-[10px] text-slate-600">{bucket.label}</span>
                            </div>
                        ))}
                    </div>
                )}
            </Panel>
        </div>
    );
}

export default Analytics;
