import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Search, Plus, Rocket, FolderOpen, AlertTriangle, X } from "lucide-react";

import PageHeader from "../components/ui/PageHeader";
import EmptyState from "../components/ui/EmptyState";
import { Skeleton } from "../components/ui/Skeleton";
import ProjectCard from "../components/projects/ProjectCard";

import { useProjects } from "../hooks/useProjects";
import { sortByNewest } from "../lib/format";
import { cn } from "../lib/cn";

/* ==========================================================
   Projects — searchable, filterable list of real projects
========================================================== */

const FILTERS = [
    { id: "all", label: "All" },
    { id: "completed", label: "Completed" },
    { id: "running", label: "Running" },
];

function Projects() {
    const { projects, loading, error, reload } = useProjects();

    const [params, setParams] = useSearchParams();
    const query = params.get("q") || "";
    const [filter, setFilter] = useState("all");

    const visible = useMemo(() => {
        const term = query.trim().toLowerCase();

        return sortByNewest(projects).filter((project) => {
            if (filter !== "all" && (project.status || "") !== filter) {
                return false;
            }

            if (!term) return true;

            const haystack = [
                project.project_name,
                project.startup_idea,
                project.thread_id,
            ]
                .filter(Boolean)
                .join(" ")
                .toLowerCase();

            return haystack.includes(term);
        });
    }, [projects, query, filter]);

    function updateQuery(value) {
        const next = new URLSearchParams(params);

        if (value.trim()) next.set("q", value);
        else next.delete("q");

        setParams(next, { replace: true });
    }

    return (
        <div className="space-y-7">
            <PageHeader
                eyebrow="Library"
                title="Projects"
                description="Every startup generated by your account, newest first."
                actions={
                    <Link to="/generate" className="btn-primary text-sm">
                        <Plus size={16} />
                        New Startup
                    </Link>
                }
            />

            {/* ---------- Toolbar ---------- */}
            <div className="panel flex flex-col gap-4 p-4 sm:flex-row sm:items-center">
                <div className="flex flex-1 items-center gap-2.5 rounded-xl border border-slate-400/12 bg-black/30 px-3.5 py-2.5 transition focus-within:border-violet-400/60">
                    <Search size={15} className="shrink-0 text-slate-500" />

                    <input
                        value={query}
                        onChange={(event) => updateQuery(event.target.value)}
                        placeholder="Search by name, idea or thread id…"
                        className="w-full bg-transparent text-sm text-slate-200 placeholder:text-slate-600"
                    />

                    {query && (
                        <button
                            onClick={() => updateQuery("")}
                            className="shrink-0 text-slate-500 transition hover:text-slate-300"
                            aria-label="Clear search"
                        >
                            <X size={15} />
                        </button>
                    )}
                </div>

                <div className="flex items-center gap-2">
                    {FILTERS.map((item) => (
                        <button
                            key={item.id}
                            onClick={() => setFilter(item.id)}
                            className={cn(
                                "rounded-xl px-4 py-2 text-xs font-semibold transition",
                                filter === item.id
                                    ? "bg-violet-500/15 text-violet-200 ring-1 ring-inset ring-violet-400/35"
                                    : "text-slate-400 ring-1 ring-inset ring-slate-400/12 hover:text-slate-200"
                            )}
                        >
                            {item.label}
                        </button>
                    ))}
                </div>
            </div>

            {/* ---------- States ---------- */}
            {loading && (
                <div className="space-y-4">
                    {[0, 1, 2, 3].map((key) => (
                        <Skeleton key={key} className="h-[122px] w-full" />
                    ))}
                </div>
            )}

            {!loading && error && (
                <div className="panel flex items-center justify-between gap-4 p-5">
                    <div className="flex items-start gap-3">
                        <AlertTriangle size={18} className="mt-0.5 shrink-0 text-amber-400" />

                        <div>
                            <p className="text-sm font-semibold text-slate-200">
                                Could not load projects
                            </p>
                            <p className="mt-0.5 text-xs text-slate-500">{error}</p>
                        </div>
                    </div>

                    <button onClick={reload} className="btn-ghost shrink-0 text-xs">
                        Retry
                    </button>
                </div>
            )}

            {!loading && !error && projects.length === 0 && (
                <EmptyState
                    icon={Rocket}
                    title="No projects yet"
                    description="Generate your first AI company and it will show up here with reports, files and a live preview."
                    action={
                        <Link to="/generate" className="btn-primary text-sm">
                            <Rocket size={16} />
                            Start generating
                        </Link>
                    }
                />
            )}

            {!loading && !error && projects.length > 0 && visible.length === 0 && (
                <EmptyState
                    icon={FolderOpen}
                    compact
                    title="No matches"
                    description="Try a different search term or clear the status filter."
                    action={
                        <button
                            onClick={() => {
                                updateQuery("");
                                setFilter("all");
                            }}
                            className="btn-ghost text-xs"
                        >
                            Reset filters
                        </button>
                    }
                />
            )}

            {!loading && !error && visible.length > 0 && (
                <>
                    <p className="text-xs text-slate-600">
                        Showing {visible.length} of {projects.length}
                    </p>

                    <div className="grid grid-cols-1 gap-4 2xl:grid-cols-2">
                        {visible.map((project) => (
                            <ProjectCard key={project.thread_id} project={project} />
                        ))}
                    </div>
                </>
            )}
        </div>
    );
}

export default Projects;

